version: '3'

services:
  zookeeper:
    image: <registry-repo>/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: <registry-repo>/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1